import sys

print("           *********           ")
print("      *****         ****       ")
print("    **                  **     ")
print("   *                      *    ")
print(" **                        **  ")
print("*                            * ")
print("*                            * ")
print("**                          ** ")
print(" **  *    ****  ****    *  **  ")
print("   ** ***** ****** ***** **    ")
print("             ****              ")
print("             ****              ")
print("             ****              ")
print("             ****              ")
print("            ******             ")
print("           ********")